name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch: {} # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build # Adjust this command based on your build setup

      - name: Run Tests
        run: npm test -- --watchAll=false # Adjust this command based on your testing setup

